import XCTest
@testable import Tablo

/// Decodes ContractFixtures/*.json — payloads the backend's own Effect schemas
/// encoded (scripts/lib/wire-fixtures.ts, regenerated by `bun run contract:write`),
/// so a backend change the app can't read fails here, not on a phone.
///
/// Assert values, not just that decoding succeeded: `Lossy` arrays skip entries
/// that fail and some fields fall back to defaults, so a renamed key would
/// otherwise decode "fine" into an empty list or a default.
final class ContractTests: XCTestCase {
    private func fixture(_ name: String) throws -> Data {
        let url = try XCTUnwrap(
            Bundle(for: ContractTests.self).url(forResource: name, withExtension: "json"),
            "missing ContractFixtures/\(name).json"
        )
        return try Data(contentsOf: url)
    }

    private func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try Wire.decode(type, from: fixture(name))
    }

    // MARK: Stop index

    func testStopsManifest() throws {
        let m = try decode(StopsManifest.self, "stops-manifest")
        XCTAssertEqual(m.path, "/data/stop-index-b9cfa9fa.json")
        XCTAssertEqual(m.generatedAt, "2026-10-03T03:00:00.000Z")
        XCTAssertEqual(m.count, 2)
    }

    func testStopIndex() throws {
        let file = try decode(StopIndexFile.self, "stop-index")
        XCTAssertEqual(file.version, 1)
        XCTAssertEqual(file.stops.count, 2)

        let nt = file.stops[0]
        XCTAssertEqual(nt.name, "Národní třída")
        XCTAssertEqual(nt.norm, "narodni trida")
        XCTAssertEqual(nt.key, "539")
        XCTAssertNil(nt.stops)
        XCTAssertEqual(nt.coord, LngLat(14.41992, 50.08069))
        XCTAssertEqual(nt.zone, "P")
        XCTAssertNil(nt.disambig)
        XCTAssertEqual(nt.platforms.map(\.code), ["A", "B"])
        XCTAssertEqual(nt.platforms.map(\.stop), [1, 2])
        XCTAssertEqual(nt.platforms[0].coord, LngLat(14.4189, 50.0813))

        let bv = file.stops[1]
        XCTAssertEqual(bv.key, "2154:301")
        XCTAssertNil(bv.zone)
        XCTAssertEqual(bv.disambig, "5")
        XCTAssertTrue(bv.platforms.isEmpty)
    }

    // MARK: WebSocket

    /// What the app sends must be what the backend's schema produces (and so accepts).
    func testClientMessagesMatchTheContract() throws {
        let subscribe = ClientMessage.subscribe([StopSelector(node: 539, stops: nil), StopSelector(node: 1040, stops: [1, 2])])
        try assertSameJSON(subscribe.json, fixture("ws-subscribe"))
        try assertSameJSON(ClientMessage.unsubscribe.json, fixture("ws-unsubscribe"))
    }

    func testDeparturesUpdate() throws {
        guard case let .departures(u) = try decode(ServerMessage.self, "ws-departures-update") else {
            return XCTFail("not a DeparturesUpdate")
        }
        XCTAssertEqual(u.generatedAt, "2026-10-03T09:10:45.141Z")
        XCTAssertTrue(u.degraded)
        XCTAssertEqual(u.reason, "upstream slow")
        XCTAssertEqual(u.boards.map(\.key), ["539", "1040:1,2"])
        XCTAssertTrue(u.boards[1].departures.isEmpty)

        let deps = u.boards[0].departures
        XCTAssertEqual(deps.count, 2)

        let tram = deps[0]
        XCTAssertEqual(tram.route, "22")
        XCTAssertEqual(tram.kind, .tram)
        XCTAssertEqual(tram.headsign, "Bílá Hora")
        XCTAssertEqual(tram.scheduled, ISODate.parse("2026-10-03T09:11:00Z"))
        XCTAssertEqual(tram.predicted, ISODate.parse("2026-10-03T09:12:20Z"))
        XCTAssertEqual(tram.delaySeconds, 80)
        XCTAssertFalse(tram.isCanceled)
        XCTAssertTrue(tram.isAtStop)
        XCTAssertEqual(tram.platform, "A")
        XCTAssertEqual(tram.tripId, "22_1234_261003")

        let metro = deps[1]
        XCTAssertEqual(metro.kind, .metro)
        XCTAssertNil(metro.predicted)
        XCTAssertNil(metro.delaySeconds)
        XCTAssertTrue(metro.isCanceled)
        XCTAssertFalse(metro.isAtStop)
        XCTAssertNil(metro.platform)
        XCTAssertNil(metro.tripId)
    }

    func testHealthyDeparturesUpdate() throws {
        guard case let .departures(u) = try decode(ServerMessage.self, "ws-departures-update-healthy") else {
            return XCTFail("not a DeparturesUpdate")
        }
        XCTAssertFalse(u.degraded)
        XCTAssertNil(u.reason)
        XCTAssertTrue(u.boards.isEmpty)
    }

    func testServerError() throws {
        guard case let .serverError(message) = try decode(ServerMessage.self, "ws-server-error") else {
            return XCTFail("not a ServerError")
        }
        XCTAssertEqual(message, "too many selectors")
    }

    // MARK: REST

    func testTrip() throws {
        let trip = try decode(Trip.self, "trip")
        XCTAssertEqual(trip.tripId, "22_1234_261003")
        XCTAssertEqual(trip.headsign, "Bílá Hora")
        XCTAssertEqual(trip.stops.count, 2)
        XCTAssertEqual(
            trip.stops[0],
            TripStop(
                name: "Národní třída", lat: 50.0813, lon: 14.4189, node: 539, stop: 1, platform: "A",
                sequence: 12, arrival: 87000, departure: 87020, distance: 5.123
            )
        )
        XCTAssertEqual(
            trip.stops[1],
            TripStop(
                name: "Rail waypoint", lat: 50.1, lon: 14.5, node: nil, stop: nil, platform: nil,
                sequence: 13, arrival: 87100, departure: 87100, distance: 5.9
            )
        )
        XCTAssertEqual(trip.shape, [ShapePoint(lon: 14.4189, lat: 50.0813, km: 5.1), ShapePoint(lon: 14.4176, lat: 50.0811, km: 5.2)])
    }

    func testTripVehicle() throws {
        XCTAssertEqual(
            try decode(TripVehicle.self, "trip-vehicle"),
            TripVehicle(
                tripId: "22_1234_261003", lat: 50.08, lon: 14.42, bearing: 250, delaySeconds: 45,
                lastStopSequence: 11, nextStopSequence: 12, distance: 4.9, state: "on_track",
                updatedAt: ISODate.parse("2026-10-03T09:10:45.000Z")
            )
        )
        XCTAssertEqual(
            try decode(TripVehicle.self, "trip-vehicle-untracked"),
            TripVehicle(
                tripId: "22_1234_261003", lat: 50.08, lon: 14.42, state: "before_track",
                updatedAt: ISODate.parse("2026-10-03T09:10:45.000Z")
            )
        )
    }

    func testLiveVehicles() throws {
        let list = try decode(LiveVehicles.self, "live-vehicles")
        XCTAssertEqual(list.generatedAt, "2026-10-03T09:10:45.000Z")
        XCTAssertEqual(
            list.vehicles,
            [
                LiveVehicle(
                    tripId: "9_1", route: "9", kind: .tram, lat: 50.08, lon: 14.42, bearing: 90, delaySeconds: 30,
                    lastStopSequence: 12, nextStopSequence: 13, distance: 5.831, state: "at_stop",
                    updatedAt: ISODate.parse("2026-10-03T11:10:31+02:00")
                ),
                LiveVehicle(
                    tripId: "136_1", route: "136", kind: .bus, lat: 50.1, lon: 14.4,
                    state: "on_track", updatedAt: ISODate.parse("2026-10-03T11:09:58+02:00")
                ),
            ]
        )
    }

    func testErrorBodies() throws {
        XCTAssertEqual(try decode(APIErrorBody.self, "error-trip-not-found").tag, "TripNotFound")
        let unavailable = try decode(APIErrorBody.self, "error-upstream-unavailable")
        XCTAssertEqual(unavailable.tag, "UpstreamUnavailable")
        XCTAssertEqual(unavailable.reason, "rate limited")
    }

    // MARK: Helpers

    /// Equal as JSON values — key order and whitespace aside.
    private func assertSameJSON(_ text: String, _ expected: Data, file: StaticString = #filePath, line: UInt = #line) throws {
        let actual = try JSONSerialization.jsonObject(with: Data(text.utf8)) as? NSDictionary
        let wanted = try JSONSerialization.jsonObject(with: expected) as? NSDictionary
        XCTAssertNotNil(actual, file: file, line: line)
        XCTAssertEqual(actual, wanted, file: file, line: line)
    }
}
